services:
  authentication-api-integration-test:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: authentication-api-integration-test
    network_mode: "host"
    volumes:
      - .:/app
      - /home/darren/authentication:/app/Authentication/secrets
    working_dir: /app
    environment:
      - SUT=https://192.168.1.137:443
    command: [ "dotnet", "test", "--filter", "FullyQualifiedName=IntegrationTests", "--logger:trx", "--logger:html" ]