services:
  authentication-api-unit-test:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: authentication-api-unit-test
    volumes:
      - .:/app
    working_dir: /app
    command: [ "dotnet", "test", "--filter", "FullyQualifiedName=UnitTests", "--logger:trx", "--logger:html" ]