apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
      - name: authentication-api
        image: authenticationapi
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: /app/secret-volume/secrets.json
          subPath: secrets.json
          readOnly: true
        livenessProbe:
          httpGet:
            path: api/authentication/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: secret-volume
        secret:
          secretName: auth-secret
  selector:
    matchLabels:
      app: authentication-api
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-api-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: authentication-api