apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
      - name: authentication-api
        image: authenticationapi
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: /app/secret-volume/secrets.json
          subPath: secrets.json
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: auth-secret
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
       initialDelaySeconds: 10
       periodSeconds: 10
  selector:
    matchLabels:
      app: authentication-api
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31302
  selector:
    app: authentication-api